#@PydevCodeAnalysisIgnore
"""
README: this script is used to generate a .app application bundle for Mac OS X.
        To use, run ./OSX/package_osx.sh from the root directory.

This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Ilathid.pyw']
DATA_FILES = ['engine', 'pygame', 'Crypto', 'DniChamberAge.py', 'ilathid_low.gif']
OPTIONS = {'argv_emulation': True, 'iconfile': 'OSX/Ilathid.icns', 'plist':'OSX/Info.plist'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
